# Generated by Django 5.2.5 on 2025-09-02 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompts',
            options={'managed': True, 'verbose_name': 'Prompt', 'verbose_name_plural': 'Prompts'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
