"""
Django settings for django_admin_panel_nudge_app project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pz2!)=6#ss+23^e4c&i!=dbq++r3ml5ro+#f)qlmw!0s3kbkdx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_admin_panel_nudge_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_admin_panel_nudge_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
     'default': {

        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'test',         # <-- Use the database name you created in pgAdmin
        'USER': 'postgres',       # <-- Use the username you created in pgAdmin
        'PASSWORD': '0608', # <-- Use the password you set for hello_user
        'HOST': 'localhost',          # Usually 'localhost' if PostgreSQL is on your PC
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  

# Where you keep *your own* static files during development
STATICFILES_DIRS = [BASE_DIR / "static"]

# Where Django will collect *all* static files for production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Nudge App Admin",
    "site_header": "Nudge Admin Panel",
    "site_brand": "Welcome to Nudge",
    # "site_logo": "images/general-img-landscape.png",   
    "copyright": "Nudge Corp",
    "custom_css": "css/jazzmin_custom.css",

    "order_with_respect_to": [
        "admin_app.Users",
        "admin_app.Prompts",
    ],

    "icons": {
        "admin_app.Users": "fas fa-user-friends",
        "admin_app.Prompts": "fas fa-comment-dots",
    },

    "show_ui_builder": False,
    # It removes the default Django auth models from the list.
    "hide_models": [
        "auth.group",
        "auth.user"
    ],

    "hide_apps": ["django.contrib.admin"],

    # "custom_links": {
    #     "admin_app": [   # Attach links under your app (admin_app)
    #         {
    #             "name": "Statistics",        # Button name
    #             "url": "admin_dashboard",        # Named URL pattern (NOT raw /admin/dashboard/)
    #             "icon": "fas fa-tachometer-alt", # Icon
    #             "permissions": ["auth.view_user"]
    #         },
    #     ]
    # },
}


# settings.py

# Use SMTP for actual email delivery
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Gmail example (works with app passwords, not your actual Gmail password)
EMAIL_HOST = ""
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""  # generate from Google account

# Default sender
DEFAULT_FROM_EMAIL = "noreply@yourdomain.com"
